const ActionTypes = {

    // product action constant
    SET_PRODUCTS: "SET_PRODUCTS",
    FETCH_PRODUCTS_SEC: "FETCH_PRODUCTS_SEC",
    FETCH_PRODUCTS_FAIL: "FETCH_PRODUCTS_FAIL",
    SET_PRODUCTS_SEC: "SET_PRODUCTS_SEC",
    EDIT_PRODUCT :"EDIT_PRODUCT",
    EDIT_PRODUCT_SEC : "EDIT_PRODUCT_SEC",
    DELETE_PRODUCT_SEC : "DELETE_PRODUCT_SEC",
    CREATE_PRODUCT_SEC : "CREATE_PRODUCT_SEC",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",


    //promotion action constant
    FETCH_PROMOTION_SEC: "FETCH_PROMOTION_SEC",
    UPDATE_PROMOTION_SEC: "UPDATE_PROMOTION_SEC",
    DELETE_PROMOTION_SEC: "DELETE_PROMOTION_SEC",

    // authen action constant
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",
    LOGIN_PROCESS: "LOGIN_PROCESS",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",


    LOADING_TOGGLE_ACTION:"LOADING_TOGGLE_ACTION",
    STOP_LOADING_TOGGLE_ACTION:"STOP_LOADING_TOGGLE_ACTION",


    // error action
    STOP_ACTION:"STOP_ACTION",
    ERROR_:"ERROR",

    // MetaData Action
    FETCH_METADATA_ACTION_SEC:'FETCH_METADATA_ACTION_SEC',
    FETCH_METADATA_ACTION_FAIL:'FETCH_METADATA_ACTION_FAIL',

    // Cloudinary Action
    UPLOAD_PHOTO_CLOUDINARY:'UPLOAD_PHOTO_CLOUDINARY'

}

const AlertTypes ={
    ALERT_SUCCESS:'success',
    ALERT_ERROR:'error',
    ALERT_CLEAR:'ALERT_CLEAR'
}

export{
    ActionTypes,
    AlertTypes
}